/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import java.awt.Color;
import java.util.Arrays;

/**
 *
 * @author FUNKATRON
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        firstNameFieldBox = new javax.swing.JTextField();
        emailAddress = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        confirmEmailAddress = new javax.swing.JTextField();
        ConfirmEmailLabel = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        lastNameFieldBox = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        SpecialtyTextBox = new javax.swing.JTextField();
        IDTextBox = new javax.swing.JTextField();
        LastNameLabel1 = new javax.swing.JLabel();
        LastNameLabel2 = new javax.swing.JLabel();
        LastNameLabel3 = new javax.swing.JLabel();
        residencyStatusBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\FUNKATRON\\Desktop\\icon.png")); // NOI18N

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        firstNameFieldBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldBoxActionPerformed(evt);
            }
        });

        emailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressActionPerformed(evt);
            }
        });

        FirstNameLabel.setText("First Name:");

        EmailLabel.setText("Email Address:");

        PasswordLabel.setText("Password:");

        ConfirmPasswordLabel.setText("Confirm Password:");

        confirmEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEmailAddressActionPerformed(evt);
            }
        });

        ConfirmEmailLabel.setText("Confirm Email Address:");

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        lastNameFieldBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldBoxActionPerformed(evt);
            }
        });

        LastNameLabel.setText("Last Name:");

        SpecialtyTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialtyTextBoxActionPerformed(evt);
            }
        });

        IDTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextBoxActionPerformed(evt);
            }
        });

        LastNameLabel1.setText("Specialty:");

        LastNameLabel2.setText("ID:");

        LastNameLabel3.setText("Residency Status:");

        residencyStatusBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residencyStatusBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegisterButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPasswordLabel)
                                    .addComponent(EmailLabel)
                                    .addComponent(FirstNameLabel)
                                    .addComponent(ConfirmEmailLabel)
                                    .addComponent(PasswordLabel)
                                    .addComponent(LastNameLabel)
                                    .addComponent(LastNameLabel1)
                                    .addComponent(LastNameLabel2)
                                    .addComponent(LastNameLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailAddress)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(confirmEmailAddress)
                                    .addComponent(jPasswordField2)
                                    .addComponent(firstNameFieldBox)
                                    .addComponent(lastNameFieldBox)
                                    .addComponent(SpecialtyTextBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IDTextBox)
                                    .addComponent(residencyStatusBox))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameFieldBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameFieldBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpecialtyTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel3)
                    .addComponent(residencyStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmEmailLabel)
                    .addComponent(confirmEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmPasswordLabel)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterButton)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void firstNameFieldBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldBoxActionPerformed

    private void emailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressActionPerformed

    private void confirmEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmEmailAddressActionPerformed

    private void lastNameFieldBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldBoxActionPerformed

    private void SpecialtyTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialtyTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialtyTextBoxActionPerformed

    private void IDTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextBoxActionPerformed

    private void residencyStatusBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residencyStatusBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residencyStatusBoxActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        boolean [] RegisterSuccess = new boolean[7];
        final boolean [] SuccessFlag = {true,true,true,true,true,true, true};   
       
        // Both above Boolean Arrays must be true to push into database
        // If the person has already registered once already, refuses a second registration
        
        if(firstNameFieldBox.getText().equals("")){ // START OF NAMING CONDITIONAL BLOCK [0] [1]
           RegisterSuccess[0] = false;
           // If firstNameField is empty
        }
       else {
            RegisterSuccess[0] = true;
            // Remove signal to finish field, set to true
        }
       
       if(lastNameFieldBox.getText().equals("")){
           RegisterSuccess[1] = false;
           // If lastNameError is empty
       }
       else {
           RegisterSuccess[1] = true;
       }                                            // END OF NAMING CONDITIONAL BLOCK
       DBConnect check = new DBConnect();
       if(emailAddress.getText().equals("")){ // EMAIL CONDITIONAL BLOCK [2]
           RegisterSuccess[2] = false;
       } 
       else if(check.checkEmail(emailAddress.getText())){
           RegisterSuccess[2] = false;
       }
       else {
           RegisterSuccess[2] = true;
       }                                // END OF EMAIL CONDITION BLOCK
       
       if(jPasswordField1.getPassword().length == 0){ /* START OF PASSWORD CONDITIONAL BLOCK [3] */
 
            RegisterSuccess[3] = false;
            // If passwordField length is empty
        }
        else if(jPasswordField1.getPassword().length < 6){
         
            RegisterSuccess[3] = false;
            // If passwordField is less than 5 characters
        }
        else if(!Arrays.equals(jPasswordField1.getPassword(),jPasswordField2.getPassword())){
         
          RegisterSuccess[3] = false;
          // If passwordField and confirmPasswordField do not match each other
        }
        else if(Arrays.equals(jPasswordField1.getPassword(),jPasswordField2.getPassword())){
          RegisterSuccess[3] = true;
          // Set to true if the passwords match
        }
        
        if(residencyStatusBox.getText().equals("")){ // START OF NAMING CONDITIONAL BLOCK [0] [1]
           RegisterSuccess[4] = false;
           // If firstNameField is empty
        }
       else {
            RegisterSuccess[4] = true;
            // Remove signal to finish field, set to true
        }
        
        if(SpecialtyTextBox.getText().equals("")){ // START OF NAMING CONDITIONAL BLOCK [0] [1]
           RegisterSuccess[5] = false;
           // If firstNameField is empty
        }
       else {
            RegisterSuccess[5] = true;
            // Remove signal to finish field, set to true
        }
             if(IDTextBox.getText().equals("")){ // START OF NAMING CONDITIONAL BLOCK [0] [1]
           RegisterSuccess[6] = false;
           // If firstNameField is empty
        }
       else {
            RegisterSuccess[6] = true;
            // Remove signal to finish field, set to true
        }
             
        if(Arrays.equals(RegisterSuccess,SuccessFlag)){
            final char [] pass = jPasswordField1.getPassword();
            String officialpass = new String(pass);
            DBConnect statement = new DBConnect();
            statement.setRegistration(firstNameFieldBox.getText(), lastNameFieldBox.getText(), emailAddress.getText(), officialpass, SpecialtyTextBox.getText(), residencyStatusBox.getText(), IDTextBox.getText());
            LogIn lg = new LogIn(); // TODO add your handling code here:
            lg.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmEmailLabel;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField IDTextBox;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LastNameLabel1;
    private javax.swing.JLabel LastNameLabel2;
    private javax.swing.JLabel LastNameLabel3;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField SpecialtyTextBox;
    private javax.swing.JTextField confirmEmailAddress;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField firstNameFieldBox;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField lastNameFieldBox;
    private javax.swing.JTextField residencyStatusBox;
    // End of variables declaration//GEN-END:variables
}
