/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import java.awt.Color;

/**
 *
 * @author FUNKATRON
 */
public class ViewPatientInfo extends javax.swing.JFrame {

    /**
     * Creates new form ViewPatientInfo
     */
    public ViewPatientInfo() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        DBConnect db = new DBConnect();
        db.getPatientInfo(db.tempPatientID);
        DoctorID.setText("Doctor ID: " + db.tempID);
        PatientAddress.setText("Address: " + db.patientAddress);
        PatientComplaint.setText("Chief Complaint: " + db.tempComplaint);
        Treatment.setText("Treatment: " + db.tempTreatment);
        PhoneNumber.setText("Phone Number: " + db.tempPhoneNumber);
        PatientID.setText("Patient ID:" + db.tempPatientID);
        DOB.setText("DOB: " + db.patientDOB);
        PatientName.setText("Patient Name: " + db.patientFirstNameStr + " " + db.patientLastNameStr);
        
    }

    /**      /* tempPatientID;
    tempPhoneNumber;
    tempComplaint;
    tempTreatment;
    patientFirstNameStr;
    patientLastNameStr;
    patientAddress;
    patientDOB;
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdmittedLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        DoctorID = new javax.swing.JLabel();
        PatientID = new javax.swing.JLabel();
        PatientName = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        PatientAddress = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        PatientComplaint = new javax.swing.JLabel();
        Treatment = new javax.swing.JLabel();
        EditButton = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        dischargeButton = new javax.swing.JButton();

        AdmittedLabel.setText("Admitted?");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\FUNKATRON\\Desktop\\424logo.PNG")); // NOI18N

        DoctorID.setText("Doctor ID#:");

        PatientID.setText("Patient ID#:");

        PatientName.setText("Patient Name:");

        DOB.setText("DOB:");

        PatientAddress.setText("Address:");

        PhoneNumber.setText("Phone Number:");

        PatientComplaint.setText("Chief Complaint:");

        Treatment.setText("Treatment:");

        EditButton.setText("Edit Patient Info");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        dischargeButton.setText("Discharge Patient");
        dischargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dischargeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(DoctorID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatientID)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(logo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOB)
                            .addComponent(PatientName)
                            .addComponent(PatientAddress)
                            .addComponent(PhoneNumber)
                            .addComponent(PatientComplaint)
                            .addComponent(Treatment)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dischargeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OK)
                        .addGap(18, 18, 18)
                        .addComponent(EditButton)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorID)
                    .addComponent(PatientID))
                .addGap(18, 18, 18)
                .addComponent(PatientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(PhoneNumber)
                .addGap(18, 18, 18)
                .addComponent(PatientComplaint)
                .addGap(62, 62, 62)
                .addComponent(Treatment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditButton)
                    .addComponent(OK)
                    .addComponent(dischargeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        UpdatePatientInfo UPI = new UpdatePatientInfo();
        UPI.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_OKActionPerformed

    private void dischargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dischargeButtonActionPerformed
        
        DBConnect db = new DBConnect();
        db.dischargePatient(db.tempPatientID);
        this.dispose();
    }//GEN-LAST:event_dischargeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatientInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatientInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdmittedLabel;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel DoctorID;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton OK;
    private javax.swing.JLabel PatientAddress;
    private javax.swing.JLabel PatientComplaint;
    private javax.swing.JLabel PatientID;
    private javax.swing.JLabel PatientName;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel Treatment;
    private javax.swing.JButton dischargeButton;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
